version: "3.9"

services:
  pdf:
    image: v2202105148987153879.supersrv.de:30311/pdf-service:latest
    container_name: pdf-service
    ports:
      - "5001:5001"
    working_dir: /usr/src/app
    networks:
      - backend
    volumes:
      - log-volume:/usr/src/app/.log
  wiki:
    image: v2202105148987153879.supersrv.de:30311/wiki-service:latest
    container_name: wiki-service
    ports:
      - "5003:5001"
    working_dir: /usr/src/app
    networks:
      - backend
    volumes:
      - log-volume:/usr/src/app/.log
  nlp-sklearn:
    image: v2202105148987153879.supersrv.de:30311/nlp-sklearn-service:latest
    container_name: nlp-sklearn-service
    ports:
      - "5101:5001"
    working_dir: /usr/src/app
    command: Server
    networks:
      - backend
    volumes:
      - log-volume:/usr/src/app/.log
networks:
  frontend:
  backend:

volumes:
  log-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .log/
