version: "3.9"

services:
  nginx:
    image: nginx:1.13.7
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
    links:
      - pdf
      - matchmaker
    depends_on:
      - pdf
      - matchmaker
  app:
    build: ./
    image: pdf2text/app
    container_name: app
    ports:
      - "5000:5001"
    links:
      - matchmaker
      - pdf
      - wiki
    depends_on:
      - pdf
      - matchmaker
      - wiki
    networks:
      - backend
      - frontend
    working_dir: /usr/src/app
    command: python3 server.py
    volumes:
      - log-volume:/usr/src/app/.log
  pdf:
    build: ./app/pdf2text/
    image: pdf2text/pdfservice
    container_name: pdf-service
    ports:
      - "5001:5001"
    working_dir: /usr/src/app
    command: python3 server.py
    networks:
      - backend
    volumes:
      - log-volume:/usr/src/app/.log
  matchmaker:
    build: ./app/Matchmaker/
    image: pdf2text/matchmaker
    container_name: match-service
    ports:
      - "5002:5001"
    working_dir: /usr/src/app
    command: Server
    networks:
      - backend
    volumes:
      - log-volume:/usr/src/app/.log
  wiki:
    build: ./app/Wiki/
    image: pdf2text/wiki
    container_name: wiki-service
    ports:
      - "5003:5001"
    working_dir: /usr/src/app
    command: python3 server.py
    networks:
      - backend
    volumes:
      - log-volume:/usr/src/app/.log
networks:
  frontend:
  backend:

volumes:
  log-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./app/.log/
