name: Build & Deploy Application (Development Version)

on:
  push:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.BASE_URL_PROD }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push to the registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.BASE_URL_PROD }}/keyword-app-service:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Image in the Cluster
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout restart deployment/keyword-app-service-deployment -n ${{ secrets.NAMESPACE_DEV }} # Reload the deployment, which takes the last version of "latest"
